
import { Inter } from 'next/font/google'
import './globals.scss'
import Footer from '@/components/Footer'
import Menu from '@/components/Menu'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="pt-br">
      <body className={inter.className} id='v1 v2'>
        <Menu/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
